# Generated by Django 5.2 on 2025-06-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_certificate'),
    ]

    operations = [
    ]
