# Generated by Django 5.2 on 2025-06-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_auto_20250628_1101'),
    ]

    operations = [
    ]
