# Generated by Django 5.2 on 2025-06-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_auto_20250628_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
