# Generated by Django 5.2 on 2025-07-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_blog_course_remove_choice_question_delete_services_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
